{
  repo1: {
      name: "My Repo 1",
      description: "This is the first repository.",
      path: "/path/to/repo1",
      branches: [
          {
              branchname: "main",
              events: ["push", "pull_request"],
              actions: {
                  action1: {
                      name: "build",
                      description: "Build the project",
                      command: "git pull && npm install && npm run build"
                  },
                  action2: {
                      name: "test",
                      description: "Run tests",
                      command: "git pull && bash deploy.sh"
                  }
              }
          }
      ]
  }
}